### ISSUE TITLE
настраиваемая отдельная папка для загрузок

### ISSUE THREAD

**Issue by rah66** [MrKsey/torrserver#5]
Здравствуйте, использую Stack /Portainer для установки с таким конфигом:

```
version: "2.1"
services:
  torrserver:
    image: ksey/torrserver
    container_name: torrserver
    network_mode: host
    environment:
      - TZ=Europe/London
    volumes:
      - /xxxxxxxxx/torrserver/db:/TS/db
    ports:
      - 8090:8090
    restart: unless-stopped
```

По сути это ваша же конфигурация, вопрос заключается в том, что можно добавить настройку для отдельной папки с закачками, чтобы файлы базы и настроек не были с закачками, кешами и т.п.  по одному пути, типа:
   volumes:
      - /xxxxxxxxx/torrserver/db:/TS/db
      - /yyyyyyyyy/torrserver/downloads:/TS/downloads
